# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  name: Restore
  inputs:
    projects: 'path/to/Yelper.sln'
    command: 'restore'
- task: DotNetCoreCLI@2
  name: Build
  inputs:
    command: 'build'
    projects: 'path/to/Yelper.sln'
- task: DotNetCoreCLI@2
  name: Tests
  inputs:
    command: 'test'
    projects: 'path/to/Yelper.sln'
    