version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=w3rystr0ngp4ss!
        - ACCEPT_EULA=Y
    ports:
        - "5434:1433"

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    environment:
        - ConnectionString=Server=sqldata;Database=Yelper.Services.IdentityDb;User Id=sa;Password=SA_PASSWORD
    depends_on:
      - sqldata
