version: '3.4'

services:
 identity.api:
  image: ${DOCKER_REGISTRY-}identityapi
  build:
   context: .
   dockerfile: Services/Identity/Identity.API/Dockerfile
  ports: 
   - "5100:80"
   - "5101:443"
  environment:
    - ConnectionString=Server=sqldata;Database=Yelper.Services.IdentityDb;User Id=sa;Password=SA_PASSWORD
  depends_on:
    - sqldata
    - rabbitmq
 
 writer.api:
  image: ${DOCKER_REGISTRY-}writerapi
  build:
   context: .
   dockerfile: Services/Writer/Writer.API/Dockerfile
  ports:
   - "5200:80"
   - "5201:443"
  depends_on:
   - rabbitmq

 rabbitmq: # login guest:guest
  image: rabbitmq:3-management
  hostname: "rabbitmq"
  labels: 
   NAME: "rabbitmq"
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

 sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=w3rystr0ngp4ss!
        - ACCEPT_EULA=Y
    ports:
        - "5434:1433"