version: '3.4'

services:
 identity.api:
  image: ${DOCKER_REGISTRY-}identityapi
  build:
   context: .
   dockerfile: Services/Identity/Identity.API/Dockerfile
  ports: 
   - "5100:80"
   - "5101:443"
  environment:
    - ConnectionStrings__Database=Data Source=identity.api.mssql;User ID=sa;Password=w3rystr0ngp4ss!;Encrypt=False;Trust Server Certificate=False;
    - rabbitmq
  depends_on:
    - identity.sqldata

 identity.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "identity.api.mssql"
    ##command: ["dotnet", "ef", "database", "update", "--no-build", "--project", "MyApp.csproj"]
    environment:
        #- SA_PASSWORD=w3rystr0ngp4ss!
        - ACCEPT_EULA=Y
    ports:
        - "5434:1433"

 writer.api:
  image: ${DOCKER_REGISTRY-}writerapi
  build:
   context: .
   dockerfile: Services/Writer/Writer.API/Dockerfile
  environment:
    - ConnectionString=Server=identity.sqldata;Database=Yelper.Services.IdentityDb;User Id=sa;Password=SA_PASSWORD
  ports:
   - "5200:80"
   - "5201:443"
  depends_on:
   - writer.sqldata
   - rabbitmq

 reader.api:
  image: ${DOCKER_REGISTRY-}readerapi
  build:
   context: .
   dockerfile: Services/Reader/Reader.API/Dockerfile
  ports:
  - "5300:80"
  - "5301:443" 
 redis:
   image: redis
   container_name: yelper.api.redis
   ports:
   - "6379:6379"

 rabbitmq: # login guest:guest
  image: rabbitmq:3-management
  hostname: "rabbitmq"
  labels: 
   NAME: "rabbitmq"
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

 writer.sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=w3rystr0ngp4ss!
        - ACCEPT_EULA=Y
    ports:
        - "5435:1433"